stages:
  data_ingestion:
    cmd: python -m src.data.data_ingestion
    
    deps:
      - src/data/data_ingestion.py
      - src/utils/logger.py
      - src/utils/paths.py
      - ../../data/raw/rides.csv

    outs:
      - data/raw/rides.csv

  data_preprocessing:
    cmd: python -m src.data.data_preprocessing

    deps:
      - src/data/data_preprocessing.py
      - data/raw/rides.csv
  
    outs:
      - data/processed/driver_acceptance_data.csv